[project]
name = "sih-smart-scan"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ekansh", email = "ekanshkarthikeya@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
sih-smart-scan = "sih_smart_scan:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
